18F/before-you-ship

Understanding ATOs for Project Managers
This doc is still in progress, but I wanted to share it with y'all. Let's avoid stylistic edits for the time being and focus on what needs further clarification.
Gist is located here if you'd prefer that: https://gist.github.com/rjmajma/692d0478dfd7bb8dcf06#file-gistfile1-txt.
=> Create Understanding ATOs for Project Managers

README.md
=> convert readme bullets into headings

index.md
=> Fix (now public!) link to our security guide

pages/understanding_atos.md
https://www.youtube.com/watch?v=T1S52B1-NT4&list=WL&index=29
=> embed Noah's DigitalGov talk

pages/ato.md
Closes #29.
It seemed like the past few ATO issues were using a similar format, so I figured I would go ahead and formalize the ATO process with a template. I'm sure things are missing, but this is hopefully a start, which we can iterate upon.
=> create an ATO issue template

_config.yml
Broken out from #32.
**Before**
**After**
/cc @leahbannon
=> fix code block rendering

pages/ato-and-you.md
=> include points of contact in issue template

_config.yml, pages/ato-and-you.md, pages/ato.md, pages/aws.md, pages/index.md
* Fix links
* Remove hard line wrapping in AWS file
* Fix some spelling
* Fix/improve Markdown formatting
/cc @leahbannon
=> various formatting tweaks

_config.yml, _pages/ato-and-you.md, _pages/ato.md, _pages/index.md, _pages/infrastructure.md, _pages/infrastructure/aws.md, _pages/security.md, _pages/security/pii.md, _pages/temporary-notes.md, _pages/zap.md
As [discussed in Slack](https://18f.slack.com/archives/wg-documentation/p1451927226001074). Used a strategy suggested in https://github.com/jekyll/jekyll/issues/920.
/cc @mbland
=> have directory structure reflect the URLs

_config.yml, pages/static-security-analysis.md
=> Add a page on static analysis tools

CONTRIBUTING.md, _pages/index.md
I worry about this site growing in scope, so figured it would be useful to say more explicitly what the site is/isn't for. Any sort of guidance I'm missing?
Ideally, the size of this site (in terms of number of words) is the largest it will ever be.
/cc @leahbannon @mogul @DavidEBest @annahsebok
=> add more guidance about what should/shouldn't be in the site

_pages/ato/levels.md, _pages/static-security-analysis.md, go
...or at least fix the tests for them.
=> fix broken external links

_config.yml, _pages/ato.md, _pages/ato/authority-to-test.md, _pages/ato/checklist.md, _pages/ato/levels.md, _pages/ato/ssp.md, _pages/infrastructure/aws.md, _pages/security.md
/cc @stvnrlly @DavidEBest @geramirez
=> add a page on System Security Plans (SSPs)

_pages/security/pii.md
I believe it should be mother's maiden name instead of number.
=> Update pii.md - possible incorrect reference

_config.yml
=> Adding our custom styles to the site.

_config.yml, assets/css/custom.scss, assets/css/styles.scss
=> Moving custom styles into a new file.

_pages/ato/background.md, _pages/laws.md, _pages/security.md
Hopefully they will be cleaned up sooner than later, but figure this will help in case anyone stumbles across them in the meantime.
=> add disclaimers to old pages

_pages/ato/controls.md
Adding links for each control enumerated on the controls page. They link to their description on https://web.nvd.nist.gov/view/800-53/home.
Fixes #83
=> Linking specific ATO controls to the NIST description.

_pages/ato/delegation.md
=> minor tweak to be more explicit about the fields at the bottom of the delegation

_pages/ato.md
Now the page is arranged chronologically, and this section can be linked to directly.
/cc #94
=> move ATO re-authorization to its own sub-section

_pages/security/static-analysis.md
=> add more links to static analysis page

_config.yml, _pages/index.md, _pages/security/frameworks.md, _pages/security/static-analysis.md
=> add framework-specific guidelines

_pages/security/static-analysis.md
Links are dependent on 18f/compliance-toolkit/pull/8
=> Add instructions and links to config files

README.md
To address the "who owns this repo?" question in https://github.com/18F/before-you-ship/issues/21.
/cc @ultrasaurus
=> mention who the project is maintained by

_pages/security/static-analysis.md
Also did some minor cleanup of the headings.
/cc @micahsaul @harrisj
=> add a table comparing hosted security scanners

_pages/security/frameworks.md
Also add link to python security video.
=> Add framework specific notes for Flask

_config.yml, _pages/ato.md, _pages/ato/checklist.md, _pages/ato/levels.md, _pages/ato/ssp.md, _pages/ato/walkthrough.md
Replaces #117, using `18f-pages-internal` as the target branch.
=> pull in ATO walkthrough content, take II

_pages/ato/controls.md
@afeld : I added some notes to this page. See what you think.  -mz
=> Control for apps

Gemfile, Gemfile.lock
Just for fun. No changes in functionality.
=> upgrade gems

_pages/security/frameworks.md
Thanks to @diego- for pointing it out!
=> link to CanCanCan instead of CanCan

_pages/security/dynamic-scanning.md
As described on the [trello card](https://trello.com/c/RhXjzX9N/27-do-an-engineering-talk-demo-on-zap), this is an effort to get more out of the tech talk I did on OWASP ZAP.
=> Adding the zap talk video and fuzzer section.

_pages/ato/ssp.md
Doesn't do much, just adds links to the sample system diagrams. Do we need to add more guidance here?
=> Adding example system diagrams

_pages/security.md
I'm pretty sure this is what's intended.
=> Fixes logic of scenario

_pages/ato/checklist.md, _pages/ato/ssp.md, _pages/ato/walkthrough.md
=> incorporate new information about Compliance Masonry

_pages/security/frameworks.md
Helpful slide deck from a talk I saw at OSCON.
=> link to OWASP Top 10 deck

_pages/infrastructure.md
/cc @jezhumble @wslack @toolness
=> add general Infrastructure notes

_pages/security/dynamic-scanning.md
Note that the diff is simpler [ignoring whitespace](https://github.com/18F/before-you-ship/pull/178/files?w=1).
=> expand on manual ZAP manual scanning instructions

_pages/ato.md
=> add note about ATOs expiring

_pages/security/dynamic-scanning.md
=> clarify that either automated or manual dynamic scanning needs to be done for ATOs

_pages/infrastructure/good-production-practices.md, _pages/infrastructure/pinning-dependencies.md
Incomplete -- pushing for collaboration
@toolness @jacobian @dogweather @msecret @jseppi: please add to this branch!
=> Add skeleton for dependency pinning docs

_pages/ato/types.md
... to Cloud.gov authentication service (at the recommendation of @brittag)
=> Change MyUSA OAuth recommendation

_pages/infrastructure/monitoring.md
Tiny update for old repo name.
=> DevOps repo -> Infrastructure repo

_pages/ato/ssp.md
=> Update example SSP Authorizing Official to Noah Kunin

_pages/security/static-analysis.md
Thanks @bmcguirk for [pointing this out](https://gsa-tts.slack.com/archives/devops-public/p1476197430000284)!
https://pypi.python.org/pypi/bandit/
=> use released version of Bandit

_pages/ato/types.md
I'm _pretty_ sure this was one of the changes that came about in the recent discussions around ATOs, essentially meaning that systems can't stay in the pre-authorization phase forever. Is that right?
/cc @jezhumble @NoahKunin @porta-antiporta
=> clarify that pre-authorization means the system can't have any production data

_pages/ato/types.md
Per @jezhumble [in Slack](https://gsa-tts.slack.com/archives/infrastructure/p1476382462002090).
=> clarify that a single set of credentials for basic auth are fine

_pages/security/static-analysis.md
Re: https://github.com/18F/before-you-ship/issues/213#issuecomment-248440012.
/cc @cnelson
=> clarify that the static analysis page is security-focused

_pages/security/frameworks.md
Thanks @NoahKunin for pointing these out!
/cc @jacobian
=> link to additional framework security documentation

_pages/ato/types.md
will come back here with hyperlinks once we have a dedicated infra lead page in the handbook
=> clarity on infrastructure leads

_pages/ato/checklist.md
I've seen this pop up a few times, so it seemed worth suggesting as a step in the checklist. Of course, if this is already part of "update relevant documentation" or is different than what I'm proposing, please feel free to change/reject.
=> add "beta" label step to checklist

_pages/ato/ssp.md
=> Templatize System Owner fields in example ssp.yml

_pages/security/dynamic-scanning.md
=> Add info on how to save and import ZAP's cert

_pages/infrastructure/sandbox.md
=> link to the 18F Sandbox sign in page

_pages/security/static-analysis.md
=> Add instructions around Gemnasium

_pages/ato/types.md
...per suggestion from @noahkunin.
/cc @hollyallen
=> change 'pre-authorization' to 'pre-assessment'

_pages/ato/checklist.md
Added detail about creating the ATO folder, added more documents to create. Trying to make this list more self-service and complete.
/cc @afeld
=> More details and docs

_includes/checklist.md, _pages/ato/checklist.md
Builds on #269.
Makes it easier to edit, preview, and copy. No content changes to the checklist itself.
---
=> move the checklist to its own file

_pages/infrastructure/pinning-dependencies.md
=> Add notes about using yarn for node dep pinning

_pages/security/static-analysis.md
Just went through it with @erik-burgess and @ccostino.
=> update the Gemnasium instructions

_includes/checklist.md
=> link to SSP and Project Plan templates

_pages/ato.md
Closes https://github.com/18F/before-you-ship/issues/57.
=> add an ATO timeline

_pages/infrastructure/common-questions.md
Would be nice to fully deprecate this page in favor of having the relevant information on the cloud.gov site. I leave that to @brittag @jameshupp!
/cc @konklone
=> clean up infrastructure FAQ page

README.md, _config.yml, _includes/checklist.md, _pages/ato/checklist.md, _pages/index.md, _pages/laws/508.md, go
Wait to merge until we confirm those new URLs are up.
/cc @wslack @ccostino
=> fix references to old Pages URLs

_includes/checklist.md, _pages/ato/ssp.md
Add more guidance about how to fill it out, and move the list from the checklist to the SSP page.
Update: Closes #228.
=> expand the SSP notes

assets/css/custom.scss
=> show checkboxes in ordered lists

_includes/checklist.md
...per conversations with Joe Hoyt and @jerodweaver. Closes #315.
=> penetration tests will be performed against production, not staging

_includes/checklist.md
=> Project Plans are apparently not required

_includes/checklist.md, _pages/ato/ssp.md
Closes #254.
@gbinal @LindsayYoung @theresaanna @cmc333333 @adelevie @lauraGgit Anything else you remember coming up as feedback that isn't reflected here?
=> add more details to the system/network diagram tips

_pages/infrastructure/aws.md
Got the OK to link to this from @boberlas.
=> link to spreadsheet of AWS service approval statuses

_pages/index.md
=> link to instructions about how to get a site public on Federalist

_pages/security/static-analysis.md
This clarifies some points of confusion for me when setting up Gemnasium
=> adding some Gemnasium info

_pages/privacy.md
Add link to official PTA template rather than the proposed one.
=> Update instructions around Privacy Threshold Analysis

_includes/checklist.md, _pages/ato/ssp.md
Came up with these as I was working through the Federalist SSP with the team.
=> add more tips around the System Security Plan

_pages/ato/background.md
Changes 'jeapordized' to 'jeopardized' in _pages/ato/background.md
=> spelling fix in background.md

_config.yml, _pages/ato.md, _pages/index.md, _pages/infrastructure.md, _pages/infrastructure/federalist.md
No substantial changes to the content itself - just moving it to places where it makes more sense.
=> move non-introductory information from the homepage

_pages/infrastructure/federalist.md
=> update Federalist page

_pages/ato.md
Resolves https://github.com/18F/before-you-ship/issues/354.
Thanks @afeld !
=> Add definition for a system

_includes/checklist.md, _pages/ato.md, _pages/security/dynamic-scanning.md
Service is no longer available.
=> remove references to Compliance Viewer

_includes/decommissioning_checklist.md
Per conversation with Pranjali Desai.
=> send Disposal Notification when decommissioning a system

_pages/infrastructure/aws.md, _pages/infrastructure/good-production-practices.md
Add a section on tagging resources
=> Add information on tagging for AWS

_pages/infrastructure/aws.md
Added fix for broken link (punctuation)
=> Update tag info

_pages/infrastructure/pinning-dependencies.md
=> Update Node package pinning.

_config.yml, _pages/infrastructure/aws.md, _pages/infrastructure/certs.md, _pages/infrastructure/good-production-practices.md
=> add a page around HTTPS certificates

_pages/infrastructure/pinning-dependencies.md, _pages/security/static-analysis.md
We'll probably need to add more guidance later as we figure it out, but this is a start.
=> switch from Gemnasium to Snyk

_pages/security/static-analysis.md
Advises starting a new Snyk org per project and to add multiple files where
warranted.
=> Expand Snyk instructions a tad.

_pages/ato.md, _pages/privacy.md
...and new links. Closes #371. Closes #372.
=> update privacy information with new procedures

_pages/security/static-analysis.md
Made aware of it in https://github.com/18F/codeclimate-bandit/issues/6.
=> link to the Code Climate Bandit plugin

_pages/infrastructure/aws.md, _pages/infrastructure/sandbox.md
Chandika is no longer used. Folks should register with the #infrastructure team
instead.
https://gsa-tts.slack.com/archives/C039MHHF8/p1549413447105500
=> Remove Chandika

Gemfile, Gemfile.lock
Preview link: https://federalist-proxy.app.cloud.gov/preview/18f/before-you-ship/jquery3/
=> upgrade to Jquery v3

_pages/ato.md
`it also good` --> `it is also good`
=> Add missing word to ATO overview

_includes/ato_checklist.md
@18F/ato no longer seems to exist.
=> use new GitHub team name

_includes/ato_checklist.md
[Discussion](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1564165627027200)
=> add joining the Bug Bounty to the ATO checklist

_pages/ato/levels.md
"... impacted party is be used" -> "... impacted party is used"
=> minor grammar correction

_includes/ato_checklist.md, _pages/ato/tips.md
Required, per https://gsa-tts.slack.com/archives/C03AF5KC1/p1568244575002800.
=> add DAP to the checklist

_pages/infrastructure/aws.md
Closes https://github.com/18F/tts-tech-portfolio/issues/104.
=> add instructions for requesting new AWS accounts

_includes/decommissioning_checklist.md
cc https://github.com/18F/tts-tech-portfolio/issues/109
=> add note about redirects

_pages/infrastructure/aws.md
Closes https://github.com/18F/aws-admin/issues/25.
=> update the AWS account creation instructions

_pages/ato.md
There's an [ongoing discussion about whether the doc should live in Before You Ship or not](https://gsa-tts.slack.com/archives/CHZLJBWCV/p1577720546003800?thread_ts=1577719843.003200&cid=CHZLJBWCV); linking to it in the interim.
=> link to the "validating the path to production" doc

_config.yml, _includes/ato_checklist.md, _pages/ato/archer.md
Closes https://github.com/18F/handbook/issues/1765. Had some time on the train so knocked it out.
=> add page on RSA Archer

CONTRIBUTING.md, Dockerfile, docker-compose.yml
Was trying to get the site running locally on a freshly-wiped machine and was having issues getting Ruby installed, so went ahead and Dockerized the site.
=> do development in Docker

_pages/infrastructure/pinning-dependencies.md
Fixes https://github.com/18F/before-you-ship/issues/384.
=> fix typo around pinning dependencies

_pages/infrastructure/monitoring.md
https://github.com/18F/tts-tech-portfolio/issues/224
=> add uptime/monitoring services available to TTS

_pages/ato.md, _pages/ato/checklist.md, _pages/infrastructure/decommissioning.md
Closes https://github.com/18F/before-you-ship/issues/429.
=> update to complete task

_pages/ato.md
=> Fix typo in link protocol

_pages/infrastructure.md
closes https://github.com/18F/before-you-ship/issues/453
=> updates pricing for cloud.gov

_pages/ato/types.md, _pages/infrastructure.md, _pages/infrastructure/aws.md, _pages/infrastructure/certs.md
See last commit for the content change. The rest is just formatting.
=> refer to TTS IaaS generally rather than just AWS

_config.yml
Fixes https://github.com/18F/before-you-ship/issues/459.
=> specify the agency to load DAP

_pages/security/scanning.md
stay current with github naming conventions, see discussion:
https://news.ycombinator.com/item?id=23500093
=> stay current with github origin naming

_pages/infrastructure/aws.md
Moved to an issue template in https://github.com/18F/aws-admin/pull/57, so we should merge that one first.
=> remove AWS account creation steps

_pages/infrastructure/sandbox.md
Depends on https://github.com/18F/aws-admin/pull/66.
=> use issue template for sandbox requests

_pages/laws/508.md
Fixes #449 with options for accessibility reviews and a working link to guild request form
=> A11y review updates

_pages/infrastructure/sandbox.md
Learned about the form through https://github.com/18F/aws-admin/issues/67#issuecomment-664614084. Also clarified that the other sandbox is for 18F specifically.
cc @saz33m
=> link to COE sandbox form

_config.yml
Adding sub-agency `TTS` for DAP
re: https://docs.google.com/document/d/1ESeQ_EaGR9RfL6Zs7pII5UFmwE0TuNwMEJDhRTg-gd8/edit
=> Specify the sub-agency for DAP

_pages/security.md
Finally got around to actually linking the lides to Before You Ship and not sure if I told @LindsayYoung how awesome she was, but definitely want to do it again. 
This closes https://github.com/18F/before-you-ship/issues/446
=> Update to include ATO slide deck

_pages/infrastructure.md
These have come up a lot recently, so wanted to get them out of my head. Adding some related reading to the ATO checklist in https://github.com/18F/tts-tech-portfolio/pull/1155.
=> elaborate on considerations for system architectures

_pages/infrastructure/federalist.md
Thought we had written this down somewhere, but wasn't sure.
=> add instructions for how to check if a site is on Federalist

_pages/ato.md
Putting here, for lack of a better place.
=> link to site redesign info

_pages/ato/ssp.md
Closes https://github.com/18F/tts-tech-portfolio/issues/1338.
Needed a place to link to the DocuSign template, so created a small section for it.
=> add section on FedRAMP packages

_pages/infrastructure/aws.md
https://github.com/18F/tts-tech-portfolio/issues/1044
Direct folks looking to use AWS to the Tech Portfolio's AWS Management guide.
=> Link to the AWS Management Guide

_pages/laws.md, _pages/laws/508.md
***
~WARNING: https://github.com/18F/handbook/pull/2538 must be merged first.~ It has been merged.
***
Closes #528 
This PR sets up redirect links from the Laws pages on BYS to the Laws page on the Handbook.
=> Set up Laws redirects

_pages/privacy.md
***
~WARNING: https://github.com/18F/handbook/pull/2539 must be merged first.~ It has been merged.
***
Closes #529
This PR sets up redirect links from the Privacy page on BYS to the Privacy page on the Handbook.
=> Set up Privacy redirects

README.md
As discussed in Slack, add a notice informing people about the recent merge. I'm open to suggestions on how to actually write this notice, formatting and specific words included.
=> Add notice to REAMDE about merge into Handbook

README.md, _config.yml, _pages/ato.md, _pages/ato/checklist.md, _pages/infrastructure/decommissioning.md, _pages/infrastructure/logging.md
https://github.com/18F/tts-tech-portfolio/issues/519
Renaming the default branch.
When ready to merge:
=> master -> main
