18F/before-you-ship

_includes/analytics.html
This changes the DAP embed code to:
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
```
This takes advantage of the DAP's new [centrally hosted JavaScript code](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/), which means 18f.gsa.gov will automatically get security updates, new features, and other bugfixes automatically.
This also tightens up the GA settings to follow [18F's standard analytics settings](https://github.com/18F/analytics-standards#javascript-code-snippet).
=> Updates DAP snippet, tightens GA settings

_config.yml, pages/aws.md, pages/infrastructure.md
Pulled directly from [the Trello card](https://trello.com/c/8o8LQrbI/273-checklist-of-prodops-best-practices-for-app-teams-with-cloud-gov-specifics), with a short intro and some formatting changes. We'll probably want to fill this out a bit (or at least link out to other places), but I think this is ok for now, just to start getting our guidelines in one place.
/cc @mogul @leahbannon
=> add page on infrastructure best practices

pages/index.md
No content changes – just rearranging things and adding headings to make the list a bit easier to digest. Probably easiest to just look at the [rendered content](https://github.com/18F/before-you-ship/blob/index-organization/pages/index.md) instead of the diff for review. Not attached to the current headings, so feel free to suggest alternatives.
/cc @leahbannon
=> split index page into categories

_config.yml, pages/ato-and-you.md, pages/ato.md, pages/aws.md, pages/pii.md, pages/security.md
This PR makes the PII page a child of the `Security` page. All links are updated to refer to the new location.
Completes #45.
=> Moved PII info from AWS page to its own page.

pages/security.md
Pipes (|) in the text were getting interpreted as markdown table separators. This replaces them with `&#124;` so they do not get interpreted.
Before:
After:
=> Replacing pipes (|) with the appropriate HTML character code.

_config.yml, _pages/ato.md, _pages/ato/authority-to-test.md, _pages/ato/background.md, _pages/ato/checklist.md, _pages/ato/levels.md, _pages/ato/tips.md, _pages/index.md, _pages/security/pii.md
This pull request splits up and rearranges the ATO-related pages.
I only made very minor changes to the content itself, so I would review this pull request for the _organization_ of the content, rather than whether each page is "complete" or not.
=> rearrange ATO pages

_config.yml, _pages/ato/checklist.md, _pages/ato/delegation.md
Closes #65.
I saw the following from @NoahKunin in [Slack](https://18f.slack.com/archives/devops/p1452463552001746):
> Re ATO delegations, since I invented it, the memo says whatever I want it to say, and will accept, which is why I wrote the boilerplate
I looked around in Drive, and found the included template in a couple of PDFs. Added some introductory language that should be checked for correctness.
/cc @wslack
=> add a page on ATO delegation

_pages/security/static-analysis.md
The PyPI version doesn't currently support the .bandit file. Or several other
configs we might want to use. Changing the install instructions to use the
github repo for now.
=> Update location for bandit install

_pages/security/static-analysis.md
Added a section for non-Rails frameworks, and walked through the basic use of DawnScanner, which supports Padrino & Sinatra.
=> Adding a section on static scanning for DawnScanner.

_pages/security/frameworks.md, _pages/security/static-analysis.md
DawnScanner currently is mostly for dependencies & Rails. We shouldn't recommend it for non-Rails apps. Adding a bit of info to the frameworks page regarding best practices for Sinatra & Padrino.
=> Removed DawnScanner from the tools list and added Sinatra framework advice

CONTRIBUTING.md, _pages/security/frameworks.md, _pages/security/static-analysis.md
We don't need to call out "official govt letterhead" notes. Who/What/Where/Why for purely informational pages seems like overload and out of scope. 
New section on the desired flow between branches.
Minor technical updates to copyright section, to make it clear that the copyright providence of the repo is CC0 now, not some later date or version.
=> Additional clarity around PR flow, copyright, and comms.

CONTRIBUTING.md
Since I don't see an "18f-internal" branch in this repository, I'm guessing this should be "18f-pages-internal".
=> Correcting "18f-internal" to "18f-pages-internal" on contributing page

_pages/index.md
While starting to work on https://github.com/18F/writing-lab/issues/138, I noticed some pieces here were a little bit out of date: .about.yml recommendations, how to share info at the all-hands, and the analytics guild channel name. People will probably feel more confident about the ATO guide if other parts of the guide seem up to date too, so here's a small edit for these.
=> Updating info in homepage list of tasks

_pages/ato.md, _pages/ato/checklist.md, _pages/ato/levels.md, _pages/ato/walkthrough.md, _pages/index.md, _pages/infrastructure/aws.md
I'm working on https://github.com/18F/writing-lab/issues/138 in incremental chunks, rather than in one big pull request, so that you all can give me feedback if I head in the wrong direction. Here's a chunk! Some changes:
* The ATO homepage doesn't need a two-step guide (1. walkthrough 2. checklist) since the walkthrough explains that you'll need to do the checklist.
* The Before You Ship homepage should just link to the ATO main page - not the main page and the "tips" page, since the ATO main page should guide you to the right things to read.
* Small precision things: the "DevOps" repo is now the "Infrastructure" repo, "about.yml" is really ".about.yml", "FISMA Medium" is officially called "FISMA Moderate".
* The team doesn't usually talk about the "Director of Delivery Architecture" - …
=> Some copyedits to make ATO-related pages easier to read

_config.yml, _pages/index.md
Here's another incremental edit to help address https://github.com/18F/writing-lab/issues/138! In order to help people find the ATO and security information they need to read, I did some work sorting out the overall organization of the guide.
* I rearranged the items in the left sidebar to reflect the order of the content on these pages, especially for the ATO section - those items are now more or less in the order that they're described by the ATO overview and walkthrough.
* I renamed the homepage title from "Introduction" to "Your guide to launching software at 18F", to help readers recognize that they're in the right place (since "Before you ship" is a bit vague). In the left sidebar, I changed "Introduction" to "Overview" (since the homepage isn't just an introduction to shipping, …
=> Organizing sidebar and revising homepage

_pages/ato/types.md
Previously, the types page defined LATO as Limited ATO. It should be Lightweight ATO.
=> Updating the LATO language.

_pages/infrastructure/monitoring.md
Following on from #134 & conversation with @afeld, added stuff about
* how to organise a devops team
* setting expectations
* configuring alerts & notification channels
* linked to @abisker's escalation doc for CS
Looked at Product Guide's [Infrastructure](https://pages.18f.gov/product-guide/lifecycle-of-a-project/infrastructure/) page but realised that it may be better to link _from_ there than _to_ there. Also, need more info on the 18F Sentry instance (@jmcarp?)
=> Monitoring: Add info on devops team, alerts, notifications

CONTRIBUTING.md
Per a conversation with @NoahKunin today (or yesterday?), since this information isn't churning as much as it was, we can remove the step of needing all public deploys to go through him. After merge:
=> remove requirement of using 18f-pages-internal branch

_pages/index.md
We had been going back-and-forth for a while about the relationship between Before You Ship and the Product Guide, and the discussion in #149 made me realize that Before You Ship focuses on the technical (security, reliability, deployment, etc.) and compliance side of projects, whereas the Product Guide covers...well...everything else. Whether this particular split is _ideal_ or not, I don't know, but that is basically the current state. This pull request adds an explanation of that relationship to the reader, and removes any information that doesn't fit the new mission statement of this guide.
@abisker @annahsebok @leahbannon @melodykramer @DavidEBest What do you think of this new distinction? Feel free to let me know via [emoji …
=> clarify relationship to the Product Guide

_pages/ato/types.md
From @NoahKunin:
> That rule [around requiring auth pre-ATO] isn't meant to be dogmatic. When the app is ready to be scanned, the auth is ready to be dropped.
https://18f.slack.com/archives/compliance-toolkit/p1462988468001023
=> add caveat to requiring auth in pre-authorization stage

_pages/ato/ssp.md
When I requested access to the previously linked Google doc, @joshuabailes responded saying that the now linked document would contain MB numbers for items that bill clients.
=> Change uniqueID note to link to MASTER 18F Agreements Report

_pages/infrastructure/monitoring.md
* 18F-wide Sentry is currently out of order
* This shows the pain of self-hosting
* Recommending one over the other is helpful to developers
=> Recommend New Relic over Sentry

_pages/infrastructure/monitoring.md
Pingdom is (at least temporarily) off limits for 18F projects
=> Remove Pingdom reference

_pages/ato.md
Would prefer to be clearer and state they build and host static web pages. I don't think the term "website" is incorrect, but its more ambiguous than I'd prefer since it makes a collection of pages sound like a standalone system.
cc @NoahKunin and @jezhumble
=> Federalist and 18F Pages don't make "websites"

_pages/ato/types.md
Suggestion on language to clarify that "pre-auth" status is itself a form of Authorization to Operate.
Assumes "Zero ATO" works as a valid short-name, as an analogue (based on CC0 associations)
=> PreAuth Clarification

_pages/infrastructure/good-production-practices.md
A simple change to point to https://docs.cloud.gov/apps/production-ready/ in case it's helpful for people running into this page.
=> Link to production ready page on docs.cloud.gov

_pages/security/static-analysis.md
Per @cmc333333 in https://github.com/18F/Infrastructure/issues/651#issuecomment-242495094. Confirmed on [their site](https://www.quantifiedcode.com/) that it's shutting down:
=> remove QuantifiedCode from list of services

_pages/ato.md, _pages/ato/background.md
I am working on a rewrite of the ATO section of before you ship with two goals:
* Bring it up-to-date with current process
* Ensure it applies to all of TTS, not just 18F
* Where possible, make it useful for people working at other agencies who want an overview of the risk management process and our approach to implementing it.
This PR updates the first page of the ATO and the background section.
=> Revamed ATO main page and background page

README.md
To help people make changes even if they aren't already familiar with 18F Pages.
=> Noting standard 18F Pages site install instructions in readme

_pages/infrastructure/aws.md, _pages/infrastructure/sandbox.md
Looks like chandika has moved from chandika.apps.cloud.gov to chandika.fr.cloud.gov.
=> Update chandika links.

_pages/ato/levels.md
beta.fec.gov was listed as 'open data' but is being considered for 'moderate' now. updated 'low' example to calc, moved fec.gov to 'moderate'.
=> new examples for ato levels

_includes/checklist.md, _pages/ato/checklist.md
This pull request adds a bunch of items to the checklist, including new items to reflect what happens around and during the Sprint, as well as detailed tasks that should have been in there even before the Sprints were implemented. I recommend reviewing using the [rich diff](https://github.com/blog/1784-rendered-prose-diffs).
* Addresses parts of
* https://github.com/18F/before-you-ship/issues/57
* https://github.com/18F/before-you-ship/issues/191
* https://github.com/18F/before-you-ship/issues/255
* https://github.com/18F/before-you-ship/issues/259
* Closes https://github.com/18F/before-you-ship/issues/182.
* Closes https://github.com/18F/before-you-ship/issues/262.
* Closes https://github.com/18F/before-you-ship/issues/263.
* Closes https://github.com/18F/before-you-ship/issues/265.
=> expand the ATO checklist

_pages/infrastructure/pinning-dependencies.md
Oops :(
Also very slightly modified the linked text to be more similar to that in the Ruby section.
=> Add missing 'be' in section on yarn in pinning-dependencies.md

_includes/checklist.md, _pages/ato.md, _pages/ato/ssp.md
Builds on https://github.com/18F/before-you-ship/pull/291. Closes https://github.com/18F/before-you-ship/issues/197.
While it's a little bit of a bummer to move away from machine-readable documentation, I don't think the `system-security-plan.yml` was adding a lot of value, or event really in use. Let's remove the overhead for now.
=> deprecate the system-security-plan.yml

_pages/security/static-analysis.md
Looks like whatever markdown renderer this uses doesn't properly handle code block language hints. Notice the spurious `javascript` shown in the screenshot below:
=> Remove markdown javascript language hint from gemnasium hack code block

_includes/checklist.md
The old link when to the same document, not the folder.
=> fixing link to sprinting team folder

assets/css/custom.scss
As a result of upgrading `guides_style_18f` to use the USWDS, the disabled inputs on the checklist page made the links in their corresponding list items unclickable. This overrides those styles on the checklist page only, leaving the rest of the site reliant on the WDS default behavior. The checklist page looks like this now:
=> Fix unclickable checklist links

.circleci/config.yml
Fixes the build. Bundler must have been installed by default before, but no longer.
=> install Bundler in CircleCI

_config.yml, _includes/checklist.md, _pages/infrastructure/good-production-practices.md, _pages/infrastructure/logging.md
Closes #284.
Adding a page with requirements and recommendations for logging, and linking there from the ATO checklist to ensure it's completed. Paired on this with @LindsayYoung and @LinuxBozo through the DevOps Guild.
=> add page around logging

_pages/security/dynamic-scanning.md, _pages/security/frameworks.md, _pages/security/static-analysis.md
**[Preview](https://federalist-proxy.app.cloud.gov/preview/18f/before-you-ship/deps/security/static-analysis/)**
In no particular order:
* Flipped the table to list available services by language, rather than the other way around.
* This is more user-centered, as users will come in thinking "I'm using X language(s) - what do I do?"
* Add recommendation for Go - closes #213
* Remove references to channel that previously maintained the site
* Update recommended JavaScript scanning tools /cc #320
* Move the headings up a level (`h3`s to `h2`s, etc.)
* Remove instructions that can be found in the canonical source
* Leaving them in, we risk them getting out-of-date
=> update the static analysis page

_includes/checklist.md, _pages/ato.md, _pages/ato/tips.md
`.about.yml` was an 18F-specific effort toward machine-readable data that no machines are reading anymore. For ATO purposes, the relevant information is in your System Security Plan. I recommend removing `.about.yml` from the ATO checklist and other tasks, so that we aren't asking people to do unnecessary work.
cc @andrewmaier @afeld
=> Remove .about.yml tasks

_pages/security/dynamic-scanning.md
Changes:
* Remove lingering mention of "automated" scans in the introduction.
* Update Slack instance name.
* Remove instruction to mark false positives within ZAP. My understanding is that in relevant ATO processes, the right step is to document the false positives separately instead of marking them as false positives within ZAP.
* Add the optional step of reporting false positives to the ZAP team.
=> Minor updates for ZAP instructions

_pages/infrastructure/pinning-dependencies.md
Promote `Pipenv`, but continue to document `pip-tools`.
=> Update Python Pinning docs

_pages/index.md
Fixes #382 
I think most of the Lifecycle section was removed from the product guide so there's nowhere to update the link to. Removing it instead. When the link was originally added, here's what the content looked like https://github.com/18F/product-guide/tree/15497b5120bac298f4b4dcecf4be5874f1d788a0/pages
=> Remove broken link to lifecycle guide

_includes/ato_checklist.md, _pages/ato.md, _pages/ato/types.md, _pages/infrastructure/logging.md
Insight seems to have been re-organized, and thus the link and instructions on how to find the LATO procedure was wrong.  There was also an audit & accountability link that was on the same page that I found that needed changing.
=> update GSA LATO location

_pages/infrastructure/pinning-dependencies.md
Since npm 6, we can and should use `npm ci`, which is explicitly about installing from the lockfile.  This PR says that and notes some buggy behavior in older npm clients.
=> Update dependency pinning notes for npm

_pages/infrastructure.md
Prior link was no longer valid.  Updated with what looks like the new marketplace link.
=> Update link to FedRAMP Authorization

_pages/infrastructure/monitoring.md
this page linked to a new relic installation that hadn't been updated in 6 years and so probably isn't the best case scenario
=> remove ref to the fisma-ready new relic instructions

_pages/infrastructure/certs.md
GSA IT can provide internal or external certificates. In the form you can specify Internal or External as the type of certificate.
=> Clarify GSA TLS certificates

.github/workflows/stale.yml
https://github.com/18F/tts-tech-portfolio/issues/1375
Remove the debug option, output looks like it's ignoring issues correctly.
Here's the log from the last run https://github.com/18F/before-you-ship/runs/2790858902?check_suite_focus=true
It identified the 4 open issues and correctly ignored them as stale because we've set `days-before-issue-stale: -1` and only want to mark PRs as stale for the moment. This appears to be working as expected, so let's enable it and continue to monitor.
=> Enable stale bot

CONTRIBUTING.md, _data/navigation.yml, _pages/ato.md, _pages/ato/archer.md, _pages/ato/checklist.md, _pages/ato/ssp.md, _pages/ato/tips.md, _pages/ato/types.md, _pages/security/mfa.md
***
~WARNING: https://github.com/18F/handbook/pull/2526 must be merged first.~ It has been merged.
***
Closes #525 
This PR sets up a redirect link from the Lifecycle pages on BYS to the Lifecycle page on the Handbook.
=> Merge Lifecycle of a Launch into Handbook

_pages/security.md, _pages/security/dynamic-scanning.md, _pages/security/frameworks.md, _pages/security/mfa.md, _pages/security/scanning.md, _pages/security/static-analysis.md
***
WARNING: https://github.com/18F/handbook/pull/2531 must be merged first.
***
Closes #526 
This PR sets up redirect links from the Security pages on BYS to the Security page on the Handbook.
=> Merge Security into Handbook

_pages/infrastructure.md, _pages/infrastructure/aws.md, _pages/infrastructure/certs.md, _pages/infrastructure/decommissioning.md, _pages/infrastructure/domains.md, _pages/infrastructure/federalist.md, _pages/infrastructure/good-production-practices.md, _pages/infrastructure/logging.md, _pages/infrastructure/monitoring.md, _pages/infrastructure/pinning-dependencies.md, _pages/infrastructure/sandbox.md
Closes #527 
This PR sets up redirect links from the Infrastructure pages on BYS to the Infrastructure page on the Handbook.
=> Set up Infrastructure redirects

_pages/ato.md, _pages/ato/archer.md, _pages/ato/checklist.md, _pages/ato/ssp.md, _pages/ato/tips.md, _pages/ato/types.md, _pages/security.md, _pages/security/dynamic-scanning.md, _pages/security/frameworks.md, _pages/security/mfa.md, _pages/security/scanning.md, _pages/security/static-analysis.md
With the URL/directory changes to the Handbook content, the redirects lead to 404s. This PR fixes that.
=> Fix broken redirect links
